Repository openshift/managed-prometheus-exporter-dns, pull requests merged in 2019-03, with the labels that each got.

#1 SREP-923: Migrate the dns latency exporter
  .gitignore
  Makefile
  README.md
  functions.mk
  monitor/main.py
  monitor/start.sh
  resources/010_serviceaccount-rolebinding.yaml.tmpl
  resources/040_daemonset.yaml.tmpl
  resources/050_service.yaml.tmpl
  resources/060_servicemonitor.yaml.tmpl
Labels: size/L

#3 Ensure the deploy directory exists
  deploy/.gitkeep
Labels: kind/bug, size/XS

#4 Update init container image to redhat quay.io org
  Makefile
Labels: kind/cleanup, size/XS

#5 Removed ref to initcontainer as it's not used
  Makefile
Labels: size/XS
