Repository openshift/managed-prometheus-exporter-dns, pull requests merged in 2019-05, with the labels that each got.

#7 Updated OWNERS to be consistent with SRE operators
  OWNERS
Labels: lgtm, size/XS

#6 Added selectorsyncset generation
  .gitignore
  Makefile
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: approved, lgtm, size/M

#8 Added all requirements for app-sre pipeline
  .gitignore
  Makefile
  hack/00-osd-managed-prometheus-exporter-dns.selectorsyncset.yaml.tmpl
  hack/app_sre_build_deploy.sh
  hack/app_sre_pr_check.sh
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: size/L

#9 Fix name of selector sync set
  hack/00-osd-managed-prometheus-exporter-dns.selectorsyncset.yaml.tmpl
  scripts/templates/selectorsyncset.yaml
Labels: size/XS
